name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        default: staging
        required: true
        type: string
    secrets:
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true
      SSH_KEY:
        required: true
      ACCESS_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script_stop: true
          script: |
            cd ~/apps/transcription/${{ inputs.environment }}/transcription-service
            git pull https://kadruko:${{ secrets.ACCESS_TOKEN }}@github.com/kadruko/transcription-service
            git checkout main
            git status
            pip install -r requirements.txt
            pm2 restart transcription-service-${{ inputs.environment }} --update-env
